forum/urls.py
from rest_framework_jwt.views import obtain_jwt_token

from forum.views import *
from django.contrib import admin
from django.urls import path
from forum.forumviews.auth import *
from forum.forumviews.forum_rest_views import *

app_name='forum'

urlpatterns = [
    path('hello/',helloview,name="hello"),
    path("signup/",SignUpFormView.as_view(),name="signup_form"),
    path("login/",LoginFormView.as_view(),name="login_form"),
    path("logout/",logout_view,name="logout"),
    path("api/v1/forum",PostsSerializerView.as_view(),name="posts_view"),
    path("api/v1/forum/posts/<int:pk>/comments",CommentsSerializerView.as_view(),name="comments_view"),
    path("api/v1/forum/posts/<int:pk>",PostDetailSerializerView.as_view(),name="postdetail_view"),
    path("api/v1/forum/posts/<int:pk>/comments/<int:id>",CommentDetailSerializerView.as_view(),name="commentdetail_view"),
    path("api/v1/forum/users/<int:pk>",UserDetailSerializerView.as_view(),name="userdetail_view"),
    path("api/v1/forum/users",UserSerializerView.as_view(),name="user_view"),
    path("api/v1/login",obtain_jwt_token,name="authenticate_user"),
    path("api/v1/signup",UserSerializerView.as_view(),name="user_signup"),
    path("api/v1/forum/posts/<int:pk>/vote",PostVoteSerializerView.as_view(),name="post_vote"),
    path("api/v1/forum/posts/<int:pk>/comments/<int:id>/vote",CommentVoteSerializerView.as_view(),name="comment_vote"),
    path("api/v1/forum/posts/<int:pk>/comments/<int:id>/accept",CommentAccept.as_view(),name="comment_accept"),
    path("api/v1/forum/posts/<int:pk>/comments/<int:id>/unaccept",CommentUnaccept.as_view(),name="comment_unaccept"),
    path("api/v1/forum/posts/<int:pk>/close",ClosePost.as_view(),name="close_post"),
    path("api/v1/forum/posts/<int:pk>/open",OpenPost.as_view(),name="open_post"),
    path("api/v1/forum/users/<int:pk>/posts",UserPostsSerializerView.as_view(),name="user_posts"),
    path("api/v1/forum/users/<int:pk>/comments",UserCommentsSerializerView.as_view(),name="user_comments"),
]

onlineforum/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.views.generic import TemplateView

from forum.forumviews.forum_rest_views import FrontendAppView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('forum.urls')),
    #url(r'^', TemplateView.as_view(template_name="index.html")),
    url(r'^', FrontendAppView.as_view()),
]

forum/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    bio=models.TextField(max_length=500,null=True)
    postkarma=models.IntegerField(default=0)
    commentkarma=models.IntegerField(default=0)

    def __str__(self):
        return self.user.username
    pass


class Post(models.Model):
    title=models.CharField(max_length=100,blank=False)
    body=models.TextField(blank=False)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="user_post")
    created=models.DateTimeField(auto_now_add=True)
    modified=models.DateTimeField(auto_now=True)
    closed=models.BooleanField(default=False)
    upvotedby=models.ManyToManyField(User,blank=True,related_name="post_upvoted_by")
    downvotedby=models.ManyToManyField(User,blank=True,related_name="post_downvoted_by")
    votes=models.IntegerField(default=0)
    accepted=models.BooleanField(default=False)

    def __str__(self):
        return self.title
    pass

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name="user_comment")
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="post_comment")
    text=models.TextField(blank=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    upvotedby = models.ManyToManyField(User, blank=True, related_name="comment_upvoted_by")
    downvotedby = models.ManyToManyField(User, blank=True, related_name="comment_downvoted_by")
    votes = models.IntegerField(default=0)
    accepted=models.BooleanField(default=False)

    def __str__(self):
        return self.post.title+" "+self.user.username
    pass

forum/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def helloview(request):
    helloworld= "<h1>helloworld</h1>"
    #return helloworld
    return HttpResponse(helloworld)

class AddPost():
    pass

forum/templates/addcollege.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit"/>
</form>
<a class="btn btn-default" href="{% url 'onlineapp:logout' %}" style="position: absolute; top: 0px; right: 0px;">Logout</a>
</body>
</html>

forum/templates/addstudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ student_form.as_p }}
    {{ mock_form.as_p}}
    <input type="submit" value="submit"/>
</form>
<a class="btn btn-default" href="{% url 'onlineapp:logout' %}" style="position: absolute; top: 0px; right: 0px;">Logout</a>
</body>
</html>

forum/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}

{% endblock content %}

</body>
</html>

forum/templates/college_confirm_delete.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit"/>
</form>

</body>
</html>

forum/templates/collegelist.html
<html>
<head>
    <title>
        College list
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<center>
    <h1>Colleges</h1>
    {% if "onlineapp.add_college" in user_permissions %}
    <a class="btn btn-default" href="{% url 'onlineapp:add_college' %}">Add College</a>
    {% endif %}
<table class="table table-hover" border="1px solid" style="border-collapse:collapse" cellpadding="10px">
<tr>
    <th>
        College Name
    </th>
    <th>
        Acronym
    </th>
    <th>
        Edit
    </th>
    <th>
        Delete
    </th>
</tr>
<tr>
    {% for i in college%}
    <td>
        <a href="{% url 'onlineapp:student_detailview' i.id %}">{{ i.name }}</a>
    </td>
    <td>
        {{ i.acronym }}
    </td>
    {% if "onlineapp.change_college" in user_permissions %}
    <td>
        <a class="btn btn-default" href="{% url 'onlineapp:update_college' i.id %}">Edit</a>
    </td>
    {% endif %}
    {% if "onlineapp.delete_college" in user_permissions %}
    <td>
       <a class="btn btn-default" href="{% url 'onlineapp:delete_college' i.id %}">Delete</a>
    </td>
    {% endif %}
</tr>
    {%endfor%}
</table>
    <a class="btn btn-default" href="{% url 'onlineapp:logout' %}" style="position: absolute; top: 0px; right: 0px;">Logout</a>
</center>
</body>
</html>

forum/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
invalid credentials
</body>
</html>

forum/templates/login.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit"/>
</form>
<br>
<a href="{% url 'forum:signup_form' %}">Signup here</a>
</body>
</html>

forum/templates/signup.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<form class="form-group"  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit"/>
</form>
<br>
<a href="{% url 'forum:login_form' %}">Login here</a>

</body>
</html>

forum/templates/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<center>
    <h1>Students</h1>
<table class="table table-hover" border="1px" style="border-collapse:collapse" cellpadding="10px">
    {% if "onlineapp.add_student" in user_permissions %}
<a href="{% url 'onlineapp:add_student2' college_id %}">Add Student</a>
    {% endif %}
    <tr>
        <th>
            Student Name
        </th>
        <th>
            Email
        </th>
        <th>
            total
        </th>
        <th>
            Edit
        </th>
        <th>
            Delete
        </th>
    </tr>
    {% for i in student %}
<tr>
    <td>
        {{ i.name }}
    </td>
    <td>
        {{ i.email }}
    </td>
    <td>
        {{ i.mocktest1__total }}
    </td>
    {% if "onlineapp.change_student" and "onlineapp.change_mocktest1" in user_permissions %}
    <td>
        <a href="{% url 'onlineapp:update_student' college_id i.id %}">Edit</a>
    </td>
    {% endif %}
    {% if "onlineapp.delete_student" and "onlineapp.delete_mocktest1" in user_permissions %}
    <td>
        <a href="{% url 'onlineapp:delete_student' college_id i.id %}">Delete</a>
    </td>
    {% endif %}
</tr>
    {% endfor %}
</table>
</center>
<a class="btn btn-default" href="{% url 'onlineapp:logout' %}" style="position: absolute; top: 0px; right: 0px;">Logout</a>
</body>
</html>

forum/templates/test.html
{% extends "base.html" %}

{% block content %}

<center> asd </center>


{% endblock content %}

templates/index.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js" integrity="sha384-u/bQvRA/1bobcXlcEYpsEdFVK/vJs3+T+nXLsBYJthmdBuavHvAW6UsmqO2Gd/F9" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>-->
    <link crossorigin="anonymous" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--&lt;!&ndash;-->
      <!--manifest.json provides metadata used when your web app is added to the-->
      <!--homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/-->
    <!--&ndash;&gt;-->
    <!--&lt;!&ndash;<link rel="manifest" href="%PUBLIC_URL%/manifest.json">&ndash;&gt;-->
    <!--&lt;!&ndash;<link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">&ndash;&gt;-->
    <!--<script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>-->

    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>-->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>-->
    <!--&lt;!&ndash;<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">&ndash;&gt;-->


    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">-->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <title>Ponynote</title>
  </head>
  <body>
    <div id="root">
    </div>
      {% render_bundle 'main' %}
  </body>
</html>